# -*- coding: utf-8 -*-
"""License_Plate_Detection[Beginner].ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TKG_KyUFZYZbj_6uyOGQlRL6kpcW7_8x

#Prepare Dataset
"""

!git clone https://github.com/THU-MIG/yolov10.git

# Commented out IPython magic to ensure Python compatibility.
# %cd /content
!gdown '1MvWH-fY8SyWo7z1ulzR5EHIHTYjvBoQQ'
!mkdir License_Plate
!unzip -q '/content/chrac 2.v1i.yolov8-obb.zip' -d '/content/License_Plate'
#Source: https://universe.roboflow.com/danang-university-of-science-and-technology-75xzh/chrac-2/dataset/1/download

# Commented out IPython magic to ensure Python compatibility.
# %cd yolov10
!pip install -q -r requirements.txt
!pip install -e.

!pip install ultralytics

from ultralytics import YOLOv10
MODEL_PATH = '/content/yolov10/yolov10n.pt'
model = YOLOv10(MODEL_PATH)

YAML_PATH = '/content/License_Plate/data.yaml'
EPOCHS = 10
BATCH_SIZE = 16
IMAGE_SIZE = 640
model.train(data = YAML_PATH, epochs = EPOCHS, batch = BATCH_SIZE, imgsz = IMAGE_SIZE)

TRAINED_MODEL_PATH = '/content/yolov10/runs/detect/train7/weights/best.pt'
model = YOLOv10(TRAINED_MODEL_PATH)
model.val(data = YAML_PATH,
          imgsz = IMAGE_SIZE,
          batch = BATCH_SIZE)

IMG_SOURCE = '/content/car.jpg'
# Adjusting confidence threshold during inference
results = model(source=IMG_SOURCE)[0]
results.save('/content/result.jpg')